Improve error message when config file is not found
Fixes https://github.com/eqrion/cbindgen/issues/411

This is still sub optimal since a stack trace is shown instead of a nice error
message, but at least adds a human readable context with full file path instead
of a generic 'Unwrap() went wrong".

Before:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Now:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn\'t open config file: cbindgen.toml."', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```